# yaml-language-server: $schema=https://www.schemastore.org/traefik-v3.json

api:
  insecure: true
entryPoints:
  web:
    address: ":80"
providers:
  docker: {}
ping: {}
log:
  format: json
  level: INFO
accessLog:
  # JSON format
  format: json
tracing:
  serviceName: traefik
  otlp:
    http:
      endpoint: 'http://otel-collector:4318/v1/traces'
